### ISSUE TITLE
Bug: Fuse Splitter - Individual Children from Edging [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#188]
The fuse splitter creates 1 child/section. (34 sections = 34 children)
PRICING IS DIFFERENT AND SHOULD NOT BE!!!
SECTION HEIGHT IS INCREASING
DOESN'T DELETE ORIGINAL CHILD OF TOTAL LENTH

Should create 1 (or 2) children 
(1 section) if ends and middle are viewed as identical.
(2 sections) if ends are separate children from middle sections. 

![image](https://user-images.githubusercontent.com/114440644/209723713-e6651ab6-16de-4ecc-9bef-03f960eb20b4.png)

![image](https://user-images.githubusercontent.com/114440644/209724494-5b3753ac-3634-4125-b01b-05850f164ba8.png)

**Comment by Reyzerbit** [comment]
This is a feature not a bug. It appears you didn't realize that the edging was sloped. When edging is sloped, multiple children must be made in order to account for the different slopes, which also accounts for the varying prices. Only issue is that  the model doesn't currently reflect sloped edging, so I will fix that.
